# Task 3 — Data Cleaning

## Titanic Dataset

### Objective

The objective of this project is to clean and transform a deliberately messy Titanic dataset into a clean, consistent, and analysis-ready dataset using Python, pandas, and NumPy.

The cleaning process will include:

* Assessing the quality of the raw dataset
* Identifying and handling missing values
* Detecting and removing duplicate records
* Standardising inconsistent values and formats
* Correcting inappropriate data types
* Detecting and evaluating numerical outliers
* Validating the cleaned dataset
* Comparing the dataset before and after cleaning
* Exporting the final cleaned dataset as a new CSV file

### Dataset Used

**File:** `train.csv`

The raw dataset will be preserved throughout the analysis, and all cleaning operations will be performed on a working copy of the dataset.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/train.csv')
# df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
578,579,0,3,"Caram, Mrs. Joseph (Maria Elias)",female,NaN,1,0,2689,14.4583,NaN,C

In [ ]:
df.shape

(891, 12)

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
 11  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

## 3. Data Quality Report

Before performing any cleaning operations, the dataset was assessed to identify potential data quality issues. The assessment covers missing values, duplicate records, data types, categorical consistency, and numerical value/range anomalies.

The findings from this assessment will be used to determine the appropriate cleaning strategy for each issue.

### 3.1 Dataset Overview

### 3.2 Duplicate Records

-The dataset was checked completely  for duplicate rows.but, No duplicate rows were found, with a total of **0 duplicate records**.

-Therefore, no rows need to be removed due to exact duplication.

### 3.3 Missing Vlaues

-Missing-value findings: Age has 177 missing values (19.87%), Cabin has 687 missing values (77.10%), and Embarked has 2 missing values (0.22%). The remaining columns contain no missing values...

### 3.4 Categorical-value findings

-Categorical-value findings: The categorical columns contain consistent and valid values. No unexpected categories or inconsistent formatting were identified, so no changes were required.

### 3.5 Current finding

-Numerical-value findings: Age, SibSp, and Parch do not show obvious invalid values. Fare contains some zero values, which require further investigation before deciding whether they should be treated as errors or valid observations.

-Fare anomaly findings: Fifteen passengers have a fare of 0. These passengers were investigated using their ticket, SibSp, and Parch values. Several passengers share the same ticket numbers, while others have unique tickets. Since there is insufficient evidence to confirm that the zero fares are data-entry errors, the values were retained as valid observations.

### 3.6 Data Types
Data-type findings: The dataset contains appropriate data types overall. Integer columns with small ranges were downcast to smaller integer types to improve memory efficiency. No changes were required for categorical or floating-point columns.

### 3.7 Data Types
Data-type findings: Numeric columns were assigned appropriate integer or floating-point types based on their value ranges and meaning. Text-based columns were converted to the string dtype. Fare and Age were retained as floating-point values because they may contain decimal values

###3.8 Outlier Detection and Treatment

The IQR method was used to identify potential outliers in the numerical columns. The analysis identified 66 outliers in `Age`, 46 in `SibSp`, 213 in `Parch`, and 116 in `Fare`.

-These observations were inspected and retained because the detected values can represent legitimate passengers or travel conditions rather than data-entry errors. For example, higher values of `SibSp` and `Parch` can represent passengers traveling with larger family groups, while higher `Fare` values can be legitimate fares for higher-class passengers.

--so, **no outliers were removed or capped**.

###3.9 Before vs After Cleaning Summary

The dataset initially contained 891 rows and 12 columns. It had 866 missing values across `Age`, `Cabin`, and `Embarked`. No duplicate rows were identified.

After cleaning, all missing values were handled, the `Cabin` column was removed due to its high proportion of missing values, and no rows were removed because there were no duplicate records or confirmed invalid outliers. The cleaned dataset contains 891 rows and 11 columns with corrected data types.

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
miss_per = (df.isnull().sum() / len(df) * 100).round(2)
miss_per

PassengerId     0.00
Survived        0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age            19.87
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          77.10
Embarked        0.22
dtype: float64

### -handling missing values column by column..

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Age'].isnull().sum()

np.int64(0)

In [ ]:
df['Embarked'].mode()[0]
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Embarked'].isnull().sum()

np.int64(0)

In [ ]:
df = df.drop('Cabin', axis=1)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
print("Sex:", df['Sex'].unique())
print("Embarked:", df['Embarked'].unique())
print("Pclass:", df['Pclass'].unique())

Sex: ['male' 'female']
Embarked: ['S' 'C' 'Q']
Pclass: [3 1 2]

In [ ]:
print(df['Sex'].value_counts())
print(df['Embarked'].value_counts())
print(df['Pclass'].value_counts())
df['Fare']

Sex
male      577
female    314
Name: count, dtype: int64
Embarked
S    646
C    168
Q     77
Name: count, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [ ]:
df[['Age', 'Fare', 'SibSp', 'Parch']].describe()

              Age        Fare       SibSp       Parch
count  891.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    0.523008    0.381594
std     13.002015   49.693429    1.102743    0.806057
min      0.420000    0.000000    0.000000    0.000000
25%     22.000000    7.910400    0.000000    0.000000
50%     29.699118   14.454200    0.000000    0.000000
75%     35.000000   31.000000    1.000000    0.000000
max     80.000000  512.329200    8.000000    6.000000

In [ ]:
df[df['Fare']==0]
# df.sample(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.000000,0,0,LINE,0.0,S
263,264,0,1,"Harrison, Mr. William",male,40.000000,0,0,112059,0.0,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.000000,0,0,LINE,0.0,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,29.699118,0,0,239853,0.0,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.000000,0,0,LINE,0.0,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,29.699118,0,0,239853,0.0,S
466,467,0,2,"Campbell, Mr. William",male,29.699118,0,0,239853,0.0,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,29.699118,0,0,239854,0.0,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.000000,0,0,LINE,0.0,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,29.699118,0,0,112052,0.0,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,29.699118,0,0,239856,0.0,S
732,733,0,2,"Knight, Mr. Robert J",male,29.699118,0,0,239855,0.0,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0,S
815,816,0,1,"Fry, Mr. Richard",male,29.699118,0,0,112058,0.0,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.000000,0,0,19972,0.0,S

In [ ]:
df['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [ ]:
df[df['Fare'] == 0][
    ['PassengerId', 'Name', 'Pclass', 'Ticket', 'Fare', 'SibSp', 'Parch']
]

,PassengerId,Name,Pclass,Ticket,Fare,SibSp,Parch
179,180,"Leonard, Mr. Lionel",3,LINE,0.0,0,0
263,264,"Harrison, Mr. William",1,112059,0.0,0,0
271,272,"Tornquist, Mr. William Henry",3,LINE,0.0,0,0
277,278,"Parkes, Mr. Francis ""Frank""",2,239853,0.0,0,0
302,303,"Johnson, Mr. William Cahoone Jr",3,LINE,0.0,0,0
413,414,"Cunningham, Mr. Alfred Fleming",2,239853,0.0,0,0
466,467,"Campbell, Mr. William",2,239853,0.0,0,0
481,482,"Frost, Mr. Anthony Wood ""Archie""",2,239854,0.0,0,0
597,598,"Johnson, Mr. Alfred",3,LINE,0.0,0,0
633,634,"Parr, Mr. William Henry Marsh",1,112052,0.0,0,0
674,675,"Watson, Mr. Ennis Hastings",2,239856,0.0,0,0
732,733,"Knight, Mr. Robert J",2,239855,0.0,0,0
806,807,"Andrews, Mr. Thomas Jr",1,112050,0.0,0,0
815,816,"Fry, Mr. Richard",1,112058,0.0,0,0
822,823,"Reuchlin, Jonkheer. John George",1,19972,0.0,0,0

In [ ]:
df[df['Fare'] == 0]['Ticket'].value_counts()

Ticket
LINE      4
239853    3
112059    1
239854    1
112052    1
239856    1
239855    1
112050    1
112058    1
19972     1
Name: count, dtype: int64

In [ ]:
df['Survived'] = df['Survived'].astype('int8')
df['Pclass'] = df['Pclass'].astype('int8')
df['SibSp'] = df['SibSp'].astype('int8')
df['Parch'] = df['Parch'].astype('int8')

df['Name'] = df['Name'].astype('string')
df['Sex'] = df['Sex'].astype('string')
df['Ticket'] = df['Ticket'].astype('string')
df['Embarked'] = df['Embarked'].astype('string')

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
numeric_cols = ['Age', 'SibSp', 'Parch', 'Fare']

Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outlier_count = (
    (df[numeric_cols] < lower) |
    (df[numeric_cols] > upper)
).sum()

outlier_count

Age       66
SibSp     46
Parch    213
Fare     116
dtype: int64

In [ ]:
summary = pd.DataFrame({
    'Metric': [
        'Row Count',
        'Column Count',
        'Missing Values',
        'Duplicate Rows'
    ],
    'Before Cleaning': [
        891,
        12,
        866,
        0
    ],
    'After Cleaning': [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

summary

           Metric  Before Cleaning  After Cleaning
0       Row Count              891             891
1    Column Count               12              11
2  Missing Values              866               0
3  Duplicate Rows                0               0

In [ ]:
df.to_csv('titanic_cleaned.csv', index=False)